spring:
  application:
    name: time-ai-agent
  profiles:
    active: local
  datasource:
    url: jdbc:postgresql://rm-cn-dsr496snw000rtdo.rwlb.rds.aliyuncs.com:5432/time_ai
    username: time
    password: Bill2279498816
    driver-class-name: org.postgresql.Driver
  ai:
    #大模型接入
    dashscope:
      api-key: sk-f00cb90a8a7d443f8f244f68ecb85e99
      chat:
        options:
          model: qwen-plus
    # 向量数据库接入
    vectorstore:
      pgvector:
        index-type: HNSW
        dimensions: 1536
        distance-type: COSINE_DISTANCE
        max-document-batch-size: 10000 # Optional: Maximum number of documents per batch
    #mcp接入
    mcp:
      client:
        sse:
          connections:
            server1:
              url: http://localhost:8127
#        stdio:
#            servers-configuration: classpath:mcp-servers.json


server:
  port: 8123
  servlet:
    context-path: /api

# springdoc-openapi config
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: org.example.timeaiagent.controller

# knife4j config
knife4j:
  enable: true
  setting:
    language: zh_cn

# searchAPI
search-api:
  api-key: VnXuLNk6R6dpCsvJjWfUxfz7

# 修改日志级别，查看 Spring AI 更多调用细节
logging:
  level:
    org.springframework.ai: DEBUG